### ISSUE TITLE
Where is "afl-tee" directory?

### ISSUE THREAD

**Issue by c01dkit** [Riscure/optee_fuzzer#10]
In optee_os.diff around line 420:
```shell
+#include "../../../afl-tee/shared/info.c"
+#include "../../../afl-tee/shared/validate.c"
+
+#include "../../../afl-tee/shared/include/afl-tee-trace.h"
```
However this repo DOES NOT contain `afl-tee`. 

Besides, build.diff generates build/Makefile like this:
```shell
##########
# AFL-TEE
##########
.PHONY: afl
afl:
	cd ../afl && AFL_NO_X86=1 CC=$(AARCH64_CROSS_COMPILE)gcc make clean all

.PHONY: afl-tee
afl-tee:
	cd ../afl-tee && CC=$(AARCH64_CROSS_COMPILE)gcc make CROSS_COMPILE_S_USER=$(CROSS_COMPILE_S_USER) \
														 CROSS_COMPILE_NS_USER=$(CROSS_COMPILE_NS_USER) \
														 TEEC_EXPORT=$(OPTEE_CLIENT_EXPORT) \
														 TA_DEV_KIT_DIR=$(OPTEE_OS_TA_DEV_KIT_DIR)
```

Where are these two directories: `afl` and `afl-tee` ? This really confused me a lot.

I have modified the wrong patches, but still stuck at this problem.

**Comment by MartijnB** [comment]
Sorry, afl-tee is this repository. So ../../../afl-tee/shared == ./optee_fuzzer/shared

The afl folder just contained a copy of the afl fuzzer.

**Comment by c01dkit** [comment]
Hi @MartijnB 

Thanks for your rapid reply ~ 😄 

> The afl folder just contained a copy of the afl fuzzer.

What's the `afl fuzzer` here? Is it the same repo as optee_fuzzer?

Or, is it another repo that I have to clone from the Github?

(Is it this repo? https://github.com/google/AFL )

**Comment by MartijnB** [comment]
Yes, it is the Google repository. Nowadays I prefer to use the community maintained version afl++: https://github.com/AFLplusplus/AFLplusplus which should work as a drop-in replacement or with minimal modifications.
