### ISSUE TITLE
How to get seeds

### ISSUE THREAD

**Issue by da1234cao** [Riscure/optee_fuzzer#5]
**Question: How to get seeds as fuzzer input** 

`AFL_POST_LIBRARY=/path/to/fuzzer/afl_validate.so afl-fuzz -i /path/to/fuzzer/seeds -t 300+ -o /tmp/state -M $1 -- /path/to/fuzzer/tee_invoke_svc`

Prerequisite:
* I have applayed the patches.
* I have watched the [video](https://www.youtube.com/watch?v=7bYAwaJ7WZw) and readed the pdf.
* I have some questions,because I am not familiar with optee. But first,**I want to run it.**
* In the codes,we use `system calls as data`.

but we how to get the `system calls  data`  as fuzzer seed?
I think the `struct CTX` in `afl-tee/shared/include/afl-tee.h` maybe important.

```c
typedef struct {
    uint8_t nr;

    uint8_t __pad[3]; // It seems it's cheaper to have aligned accesses with 3 pad bytes than unaligned mem

    uint32_t arg_type; /* arg_type[TEE_SVC_MAX_ARGS]; */

    SYSCALL_ARG args[]; /* args[TEE_SVC_MAX_ARGS]; */
} SYSCALL_INVOKE __attribute__ (( aligned(8) ));

typedef struct {
    const void* const buf;
    const size_t buf_len;

    const SYSCALL_INVOKE* const cmd_first;
    const SYSCALL_INVOKE* cmd_current;

    const void* const data;
    const size_t data_len;

    char** p_error;
} CTX;

**Comment by da1234cao** [comment]
This is not a good question.
In the program.The `optee_client/libteec/src/tee_client_api.c` has been rewrite. 
As normal ca/ta,It works likes before.
However,when we define variable `AFL_TRACE_SVC` .　The second ca/ta will record the trace,which may be used as seed.

**Comment by 21212124** [comment]
Hi @da1234cao Have you been able to use the fuzzer with these patches? and use correct seeds?

**Comment by da1234cao** [comment]
**Undefined behavior out_of_bounds at core/kernel/afl_svc_trace.c:243 col 57**

1. run command `AFL_TRACE_SVC=/tmp xtest`
2. in ca:regression_4006.25 Asym Crypto case 50 algo 0x60000030 line 2962
3. in ta,there is a question:cryp_obj_populate[30](238980, *40008580:c0, 8E/TC:0 0 Undefined behavior out_of_bounds at core/kernel/afl_svc_trace.c:243 col 57
E/TC:0 0 Panic at core/kernel/ubsan.c:222 <__ubsan_handle_out_of_bounds>

**Comment by da1234cao** [comment]
fix the question like this
```c
 // off += snprintf(&buf[off], sizeof(buf) - off, " attr %x { id: %x, a: %x, b: %x }\n", attrn, attr.attribute_id, attr.a, attr.b);
int from_len;
from_len = snprintf(&buf[off], sizeof(buf) - off, " attr %x { id: %x, a: %x, b: %x }\n", attrn, attr.attribute_id, attr.a, attr.b);

if( from_len < 0 || from_len > sizeof(buf) - off)
     goto end;　　
off += from_len;
```
